const S = [
  { id:'overview', t:'Overview', c:'<h1>Snaproo</h1><p class="tl">Pure Pixel Experience Engine. Read. Optimise. Output. Every pixel. One toolkit.</p><p>Snaproo is a comprehensive image toolkit that runs 100% offline. No cloud, no accounts, no tracking.</p><h3>Core Principles</h3><ul><li><strong>100% Offline</strong> \u2014 zero network requests</li><li><strong>Private</strong> \u2014 no data leaves your device</li><li><strong>No Account</strong> \u2014 no signup, no login</li><li><strong>Lightweight</strong> \u2014 minimal permissions</li></ul><h3>Tools</h3><div class="fg"><div class="fi"><strong>Edit</strong> \u2014 Non-destructive image editor</div><div class="fi"><strong>Collage</strong> \u2014 Freeform canvas composition</div><div class="fi"><strong>Batch</strong> \u2014 Process multiple images</div><div class="fi"><strong>Convert</strong> \u2014 Format conversion</div><div class="fi"><strong>Generate</strong> \u2014 Create from scratch</div><div class="fi"><strong>Info</strong> \u2014 EXIF, metadata, hash</div><div class="fi"><strong>QR</strong> \u2014 Generate and read QR codes</div><div class="fi"><strong>Colors</strong> \u2014 Eyedropper and palette</div><div class="fi"><strong>SVG</strong> \u2014 Inspect and trace to vector</div><div class="fi"><strong>Compare</strong> \u2014 Diff and slider</div><div class="fi"><strong>Store</strong> \u2014 App store assets</div></div>' },
  { id:'edit', t:'Edit', c:'<h2>Image Editor</h2><p>Non-destructive editing \u2014 original image never modified. All operations stack and can be undone.</p><h3>Getting Started</h3><ul><li>Drop image, click browse, or <kbd>Ctrl+V</kbd> paste</li><li>Ribbon toolbar activates when image loads</li><li><kbd>Ctrl+Z</kbd> to undo any operation</li></ul><h3>Features</h3><div class="fg"><div class="fi"><strong>Resize</strong> \u2014 Non-destructive, from original</div><div class="fi"><strong>Crop</strong> \u2014 Free, ratio, or smart auto</div><div class="fi"><strong>Rotate/Flip</strong> \u2014 90\u00b0 steps</div><div class="fi"><strong>Adjust</strong> \u2014 B/C/S/H sliders</div><div class="fi"><strong>Filters</strong> \u2014 Grayscale, Sepia, Invert, Blur, Sharpen</div><div class="fi"><strong>Draw</strong> \u2014 Rect, Arrow, Text, Pen, Highlighter</div><div class="fi"><strong>Watermark</strong> \u2014 Text overlay with controls</div><div class="fi"><strong>Effects</strong> \u2014 Vignette, Denoise, Pixelate, Round</div><div class="fi"><strong>Padding</strong> \u2014 Add space around image</div><div class="fi"><strong>Export</strong> \u2014 PNG, JPEG, WebP, BMP, SVG</div></div><h3>History</h3><p>Press <kbd>H</kbd> to see all operations. Click any to revert.</p><h3>Save/Load</h3><p>Save as <code>.snaproo</code> file (original + operations). Load to continue editing later.</p><h3>Shortcuts</h3><table class="st"><tr><th>Action</th><th>Key</th></tr><tr><td>Undo</td><td><kbd>Ctrl+Z</kbd></td></tr><tr><td>Redo</td><td><kbd>Ctrl+Y</kbd></td></tr><tr><td>Export</td><td><kbd>Ctrl+S</kbd></td></tr><tr><td>Ruler</td><td><kbd>R</kbd></td></tr><tr><td>Grid</td><td><kbd>G</kbd></td></tr><tr><td>Center</td><td><kbd>C</kbd></td></tr><tr><td>History</td><td><kbd>H</kbd></td></tr></table>' },
  { id:'collage', t:'Collage', c:'<h2>Freeform Collage</h2><p>Drag-and-drop canvas. Place, resize, rotate, layer, blend images freely.</p><h3>Interaction</h3><ul><li>Click to select, drag to move, handles to resize</li><li><kbd>Shift</kbd> while resizing = lock aspect ratio</li><li><kbd>Shift+Click</kbd> = multi-select, <kbd>Ctrl+A</kbd> = select all</li><li>Double-click image = pan inside frame</li><li>Right-click = context menu</li></ul><h3>Features</h3><div class="fg"><div class="fi"><strong>Arrange</strong> \u2014 Grid, Row, Col, Stack</div><div class="fi"><strong>Templates</strong> \u2014 Polaroid, Film, Magazine</div><div class="fi"><strong>Rotate/Flip</strong> \u2014 Free rotation handle</div><div class="fi"><strong>Blend Modes</strong> \u2014 16 modes per image</div><div class="fi"><strong>Edge Fades</strong> \u2014 Independent L/R/T/B</div><div class="fi"><strong>Join Blend</strong> \u2014 Auto-fade at seams</div><div class="fi"><strong>Smart Snap</strong> \u2014 Align to edges/centers</div><div class="fi"><strong>Alignment</strong> \u2014 L/R/T/B/Center/Distribute</div><div class="fi"><strong>Group</strong> \u2014 <kbd>Ctrl+G</kbd> / <kbd>Ctrl+Shift+G</kbd></div><div class="fi"><strong>Text</strong> \u2014 Add/edit text on canvas</div></div><h3>Export</h3><p>PNG/JPEG/WebP. Trim to content option. Save/Load <code>.snaproo</code> project files.</p>' },
  { id:'batch', t:'Batch Edit', c:'<h2>Batch Processing</h2><p>Process multiple images with same settings. Checkboxes to select/deselect.</p><h3>Key Features</h3><div class="fg"><div class="fi"><strong>Pipeline Import</strong> \u2014 Apply Edit ops to all</div><div class="fi"><strong>Multi-size</strong> \u2014 Export at multiple widths</div><div class="fi"><strong>Smart Rename</strong> \u2014 {name} {index} {date} {w} {h}</div><div class="fi"><strong>Zip</strong> \u2014 Bundle all into one ZIP</div><div class="fi"><strong>Watermark</strong> \u2014 5 modes + image logo</div><div class="fi"><strong>LQIP</strong> \u2014 Lazy-load placeholders</div><div class="fi"><strong>Social</strong> \u2014 IG/FB/Twitter/YT sizes</div><div class="fi"><strong>Consistency</strong> \u2014 Find dimension outliers</div><div class="fi"><strong>Presets</strong> \u2014 Save/load settings</div><div class="fi"><strong>Duplicates</strong> \u2014 Find similar images</div><div class="fi"><strong>Batch Crop</strong> \u2014 Trim edges from all</div><div class="fi"><strong>Normalize</strong> \u2014 Same size with letterbox</div></div><h3>Workflow</h3><ol><li>Drop images (checkboxes to select)</li><li>Configure settings</li><li>Preview to verify</li><li>Process All \u2192 ZIP download</li></ol>' },
  { id:'convert', t:'Convert', c:'<h2>Format Conversion</h2><p>Convert between PNG, JPEG, WebP, BMP. Batch supported.</p><ul><li>Quality slider for lossy formats</li><li>Optional resize during conversion</li><li>Strip metadata for privacy</li></ul>' },
  { id:'generate', t:'Generate', c:'<h2>Image Generator</h2><p>Create images from scratch.</p><div class="fg"><div class="fi"><strong>Gradient</strong> \u2014 Linear/radial</div><div class="fi"><strong>Pattern</strong> \u2014 Checker/stripes/dots/noise</div><div class="fi"><strong>Placeholder</strong> \u2014 Sized with text</div><div class="fi"><strong>Social Banner</strong> \u2014 10 presets</div><div class="fi"><strong>Avatar</strong> \u2014 Circle with initials</div><div class="fi"><strong>Noise</strong> \u2014 White/Perlin/color</div><div class="fi"><strong>Favicon</strong> \u2014 Letter icon</div><div class="fi"><strong>Swatch</strong> \u2014 Color palette card</div></div>' },
  { id:'info', t:'Info', c:'<h2>Image Info</h2><ul><li>File info, dimensions, aspect ratio</li><li>EXIF data (camera, date, GPS)</li><li>DPI from PNG/JPEG headers</li><li>JPEG structure analysis</li><li>SHA-256 + perceptual hash</li><li>Copy as base64 data URI</li></ul>' },
  { id:'qr', t:'QR Code', c:'<h2>QR Code</h2><h3>Generate</h3><p>Presets: URL, WiFi, Email, Phone, vCard. Custom size, colors, error correction. Export PNG/SVG.</p><h3>Read</h3><p>Drop an image with a QR code to decode.</p>' },
  { id:'colors', t:'Colors', c:'<h2>Color Tools</h2><ul><li>Eyedropper: click any pixel</li><li>Dominant palette auto-extracted</li><li>HEX, RGB, HSL formats</li><li>Click to copy</li></ul>' },
  { id:'svg', t:'SVG Tools', c:'<h2>SVG Tools</h2><h3>Inspect</h3><p>View SVG source, dimensions, element count. Export as raster.</p><h3>Trace</h3><p>Vectorize raster images. 11 presets: Logo, Sketch, Photo, Artistic, etc.</p>' },
  { id:'compare', t:'Compare', c:'<h2>Image Compare</h2><ul><li>Side-by-side view</li><li>Pixel diff (red highlights)</li><li>Before/after slider</li><li>Center alignment guides</li></ul>' },
  { id:'shortcuts', t:'All Shortcuts', c:'<h2>Keyboard Shortcuts</h2><p>Press <kbd>Ctrl+/</kbd> anywhere to see the shortcuts overlay.</p><table class="st"><tr><th>Action</th><th>Key</th></tr><tr><td>Undo</td><td><kbd>Ctrl+Z</kbd></td></tr><tr><td>Redo</td><td><kbd>Ctrl+Y</kbd></td></tr><tr><td>Export</td><td><kbd>Ctrl+S</kbd></td></tr><tr><td>Shortcuts</td><td><kbd>Ctrl+/</kbd></td></tr><tr><td>Ruler (Edit)</td><td><kbd>R</kbd></td></tr><tr><td>Grid (Edit)</td><td><kbd>G</kbd></td></tr><tr><td>Center (Edit)</td><td><kbd>C</kbd></td></tr><tr><td>History (Edit)</td><td><kbd>H</kbd></td></tr><tr><td>Select All (Collage)</td><td><kbd>Ctrl+A</kbd></td></tr><tr><td>Group (Collage)</td><td><kbd>Ctrl+G</kbd></td></tr><tr><td>Ungroup (Collage)</td><td><kbd>Ctrl+Shift+G</kbd></td></tr><tr><td>Delete</td><td><kbd>Delete</kbd></td></tr><tr><td>Zoom (Collage)</td><td><kbd>Ctrl+Scroll</kbd></td></tr></table>' },
];

const nav = document.getElementById('nav');
const ct = document.getElementById('content');

S.forEach(s => {
  const a = document.createElement('a');
  a.className = 'help-nav-item';
  a.textContent = s.t;
  a.href = '#' + s.id;
  a.addEventListener('click', (e) => { e.preventDefault(); show(s.id); });
  nav.appendChild(a);
});

function show(id) {
  const s = S.find(x => x.id === id);
  if (!s) return;
  ct.innerHTML = s.c;
  nav.querySelectorAll('.help-nav-item').forEach(a => a.classList.toggle('active', a.hash === '#' + id));
  history.replaceState(null, '', '#' + id);
  ct.scrollTop = 0;
}

show(location.hash.slice(1) || 'overview');
